'use strict';

module.exports = {
    up: function(queryInterface, Sequelize) {

        return queryInterface.bulkInsert('drinks', [{
            name: 'Anchor Steam',
            type: 'beer',
            price: 5,
            alcohol: 13,
            sugar: 0,
            calories: 153,
            carbs: 16,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/as_y7rqwg.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Heineken',
            type: 'beer',
            price: 7,
            alcohol: 13,
            sugar: 0,
            calories: 148,
            carbs: 11,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/he_uwx8ht.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Sam Adams',
            type: 'beer',
            price: 7,
            alcohol: 13,
            sugar: 0,
            calories: 150,
            carbs: 12,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/sa_p5bezb.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Corona Extra',
            type: 'beer',
            price: 7,
            alcohol: 13,
            sugar: 0,
            calories: 148,
            carbs: 13,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/ce_lnmv0n.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Corona Light',
            type: 'beer',
            price: 7,
            alcohol: 12,
            sugar: 0,
            calories: 99,
            carbs: 5,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585303/cl_oytwew.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Miller Lite',
            type: 'beer',
            price: 7,
            alcohol: 13,
            sugar: 1,
            calories: 110,
            carbs: 7,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585304/ml_colsm4.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Budweiser',
            type: 'beer',
            price: 4,
            alcohol: 14,
            sugar: 0,
            calories: 145,
            carbs: 11,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585305/bud_nvdhsm.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Bud Light',
            type: 'beer',
            price: 4,
            alcohol: 12,
            sugar: 0,
            calories: 110,
            carbs: 7,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/bl_zuupyr.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Guinness',
            type: 'beer',
            price: 8,
            alcohol: 14,
            sugar: 18,
            calories: 215,
            carbs: 18,
            volume: 16,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/gu_b4ll4q.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Pinot Noir',
            type: 'wine',
            price: 11,
            alcohol: 14,
            sugar: 1,
            calories: 123,
            carbs: 3,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/pn_mqz3at.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Merlot',
            type: 'wine',
            price: 10,
            alcohol: 14,
            sugar: 1,
            calories: 123,
            carbs: 4,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585302/mer_qleryf.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Chardonnay',
            type: 'wine',
            price: 10,
            alcohol: 13,
            sugar: 1,
            calories: 123,
            carbs: 3,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585303/chard_eev1ya.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Pinot Grigio',
            type: 'wine',
            price: 10,
            alcohol: 14,
            sugar: 1,
            calories: 114,
            carbs: 4,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585304/pg_jsm8jb.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Cabernet Sauvignon',
            type: 'wine',
            price: 11,
            alcohol: 14,
            sugar: 1,
            calories: 115,
            carbs: 4,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585307/cab_j3jshp.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Zinfandel',
            type: 'wine',
            price: 9,
            alcohol: 14,
            sugar: 0,
            calories: 160,
            carbs: 5,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585302/zin_jtzr7v.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Syrah',
            type: 'wine',
            price: 13,
            alcohol: 13,
            sugar: 1,
            calories: 124,
            carbs: 4,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/syrah_gv8iua.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Prosecco',
            type: 'wine',
            price: 9,
            alcohol: 12,
            sugar: 0,
            calories: 150,
            carbs: 12,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/pro_pr43f7.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Champagne',
            type: 'wine',
            price: 8,
            alcohol: 8,
            sugar: 1,
            calories: 87,
            carbs: 3,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585312/cha_nmz2zg.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Long Island Iced Tea',
            type: 'mixed',
            price: 10,
            alcohol: 21,
            sugar: 9,
            calories: 180,
            carbs: 10,
            volume: 8,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585303/lit_ycdjmg.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Gin & Tonic',
            type: 'mixed',
            price: 10,
            alcohol: 15,
            sugar: 15,
            calories: 171,
            carbs: 16,
            volume: 8,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585304/gandt_zqwpg5.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Mojito',
            type: 'mixed',
            price: 14,
            alcohol: 10,
            sugar: 23,
            calories: 217,
            carbs: 8,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585305/mojito_tbzbwf.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'RedBull Vodka',
            type: 'mixed',
            price: 12,
            alcohol: 14,
            sugar: 26,
            calories: 181,
            carbs: 27,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585304/rbv_lt0ex3.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Cosmo',
            type: 'mixed',
            price: 11,
            alcohol: 18,
            sugar: 11,
            calories: 213,
            carbs: 13,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/cos_otyxaa.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Vodka Soda',
            type: 'mixed',
            price: 7,
            alcohol: 14,
            sugar: 0,
            calories: 96,
            carbs: 0,
            volume: 5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/vods_e7n54c.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'White Russian',
            type: 'mixed',
            price: 15,
            alcohol: 18,
            sugar: 16,
            calories: 257,
            carbs: 16,
            volume: 8,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458596493/whiterussian_snpqjo.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Moscow Mule',
            type: 'mixed',
            price: 14,
            alcohol: 12,
            sugar: 21,
            calories: 320,
            carbs: 34,
            volume: 10,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458596149/moscowmule_ayfvfo.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Jack and Coke',
            type: 'mixed',
            price: 15,
            alcohol: 14,
            sugar: 32,
            calories: 255,
            carbs: 32,
            volume: 12,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585304/jandc_qjhbnr.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Crown Royal',
            type: 'liquor',
            price: 6,
            alcohol: 14,
            sugar: 0,
            calories: 96,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585309/cr_x0yrha.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Captain Morgan',
            type: 'liquor',
            price: 7,
            alcohol: 9,
            sugar: 0,
            calories: 86,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585300/cm_qbc8fj.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Admiral Nelson',
            type: 'liquor',
            price: 2,
            alcohol: 9,
            sugar: 0,
            calories: 69,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585301/an_x8xkcx.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Jagermeister',
            type: 'liquor',
            price: 8,
            alcohol: 8.7,
            sugar: 0,
            calories: 103,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585302/ja_gvo8gw.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Jose Cuervo',
            type: 'liquor',
            price: 8,
            alcohol: 13,
            sugar: 0,
            calories: 96,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585303/jc_rynwep.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Jameson',
            type: 'liquor',
            price: 8,
            alcohol: 14,
            sugar: 0,
            calories: 69,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585302/jam_lipi8y.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Makers Mark',
            type: 'liquor',
            price: 8,
            alcohol: 14,
            sugar: 0,
            calories: 69,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458595788/mama_o7ivri.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Grey Goose',
            type: 'liquor',
            price: 8,
            alcohol: 13,
            sugar: 0,
            calories: 70,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585306/gg_npddvg.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }, {
            name: 'Jack Daniels',
            type: 'liquor',
            price: 7,
            alcohol: 14,
            sugar: 0,
            calories: 100,
            carbs: 0,
            volume: 1.5,
            imageurl: 'http://res.cloudinary.com/df1u5o3g6/image/upload/v1458585299/jd_j3jnu0.png',
            createdAt: new Date(),
            updatedAt: new Date()
        }]);
    },

    down: function(queryInterface, Sequelize) {
        /*
          Add reverting commands here.
          Return a promise to correctly handle asynchronicity.

          Example:
          return queryInterface.bulkDelete('Person', null, {});
        */
    }
}